syntax = "proto3";
package metapb;

import "gogoproto/gogo.proto";

option (gogoproto.marshaler_all) = true;
option (gogoproto.sizer_all) = true;
option (gogoproto.unmarshaler_all) = true;

message Cluster {
    uint64 id = 1;
    // region 的最大 peer 数量。
    // 如果 region peer 数量不匹配，调度器将进行自动平衡。
    uint32 max_peer_count = 2;
    // 更多属性......
}

enum StoreState {
    Up = 0;
    Offline = 1;
    Tombstone = 2;
}

message Store {
    uint64 id = 1;
    // 处理客户端请求的地址（kv、cop 等）
    string address = 2;
    StoreState state = 3;
}

message RegionEpoch {
    // 配置变更版本，添加或移除 peer 时自动递增
    uint64 conf_ver = 1;
    // Region 版本，分裂或合并时自动递增
    uint64 version = 2;
}

message Region {
    uint64 id = 1;
    // Region key 范围 [start_key, end_key)。
    bytes start_key = 2;
    bytes end_key = 3;
    RegionEpoch region_epoch = 4;
    repeated Peer peers = 5;
}

message Peer {      
    uint64 id = 1;
    uint64 store_id = 2;
}
