syntax = "proto3";
package raft_serverpb;

import "eraftpb.proto";
import "metapb.proto";

// Raft peer 之间发送的消息，它将 raft 消息包装并附带一些元信息。
message RaftMessage {
    uint64 region_id = 1;
    metapb.Peer from_peer = 2;
    metapb.Peer to_peer = 3;
    eraftpb.Message message = 4;
    metapb.RegionEpoch region_epoch = 5;
    // true 表示 to_peer 是一个墓碑 peer，它应该自行移除。
    bool is_tombstone = 6;
    // Region key 范围 [start_key, end_key)。（在 3B 中使用）
    bytes start_key = 7;
    bytes end_key = 8;
}

// 用于存储 Raft 的持久化状态，包括 raft 的 hard state 和 raft 日志的最后索引。
message RaftLocalState {
    eraftpb.HardState hard_state = 1;
    uint64 last_index = 2;
    uint64 last_term = 3;
}

// 用于存储 Raft 状态机的持久化状态。
message RaftApplyState {
    // 记录状态机已应用的索引，以确保重启后不会重复应用任何索引。
    uint64 applied_index = 1;
    // 记录已被截断的最后一条 raft 日志的索引和任期。（在 2C 中使用）
    RaftTruncatedState truncated_state = 2;
}

// Raft 日志压缩的截断状态。
message RaftTruncatedState {
    uint64 index = 1;
    uint64 term = 2;
}

// 用于存储 Region 信息以及此 Store 上对应的 Peer 状态。
message RegionLocalState {
    PeerState state = 1;
    metapb.Region region = 2;
}

// Normal 表示此 Peer 是正常的；
// Tombstone 表示此 Peer 已从 Region 中移除，无法加入 Raft Group。
enum PeerState {
    Normal = 0;
    Tombstone = 2;
}

// Store 的持久化标识。
// 用于重启后恢复 store id。
message StoreIdent {
    uint64 cluster_id = 1;
    uint64 store_id = 2;
}

// 快照发送和接收相关的消息。
// 不包含在课程范围内。
message KeyValue {
    bytes key      = 1;
    bytes value    = 2;
}

message RaftSnapshotData {
    metapb.Region region = 1;
    uint64 file_size = 2;
    repeated KeyValue data = 3;
    SnapshotMeta meta = 5;
}

message SnapshotCFFile {
    string cf = 1;
    uint64 size = 2;
    uint32 checksum = 3;
}

message SnapshotMeta {
    repeated SnapshotCFFile cf_files = 1;
}

message SnapshotChunk {
    RaftMessage message = 1;
    bytes data = 2;
}

message Done {}

