syntax = "proto3";
package schedulerpb;

import "metapb.proto";
import "eraftpb.proto";

import "gogoproto/gogo.proto";

option (gogoproto.sizer_all) = true;
option (gogoproto.marshaler_all) = true;
option (gogoproto.unmarshaler_all) = true;

service Scheduler {
    // GetMembers 获取此集群的成员列表。它不要求
    // 请求中的 cluster_id 与此集群的 id 匹配。
    rpc GetMembers(GetMembersRequest) returns (GetMembersResponse) {}

    rpc Tso(stream TsoRequest) returns (stream TsoResponse) {}

    rpc Bootstrap(BootstrapRequest) returns (BootstrapResponse) {}

    rpc IsBootstrapped(IsBootstrappedRequest) returns (IsBootstrappedResponse) {}

    rpc AllocID(AllocIDRequest) returns (AllocIDResponse) {}

    rpc GetStore(GetStoreRequest) returns (GetStoreResponse) {}

    rpc PutStore(PutStoreRequest) returns (PutStoreResponse) {}

    rpc GetAllStores(GetAllStoresRequest) returns (GetAllStoresResponse) {}

    rpc StoreHeartbeat(StoreHeartbeatRequest) returns (StoreHeartbeatResponse) {}

    rpc RegionHeartbeat(stream RegionHeartbeatRequest) returns (stream RegionHeartbeatResponse) {}

    rpc GetRegion(GetRegionRequest) returns (GetRegionResponse) {}

    rpc GetPrevRegion(GetRegionRequest) returns (GetRegionResponse) {}

    rpc GetRegionByID(GetRegionByIDRequest) returns (GetRegionResponse) {}

    rpc ScanRegions(ScanRegionsRequest) returns (ScanRegionsResponse) {}

    rpc AskSplit(AskSplitRequest) returns (AskSplitResponse) {}

    rpc GetClusterConfig(GetClusterConfigRequest) returns (GetClusterConfigResponse) {}

    rpc PutClusterConfig(PutClusterConfigRequest) returns (PutClusterConfigResponse) {}

    rpc ScatterRegion(ScatterRegionRequest) returns (ScatterRegionResponse) {}

    rpc GetGCSafePoint(GetGCSafePointRequest) returns (GetGCSafePointResponse) {}

    rpc UpdateGCSafePoint(UpdateGCSafePointRequest) returns (UpdateGCSafePointResponse) {}

    rpc GetOperator(GetOperatorRequest) returns (GetOperatorResponse) {}
}

message RequestHeader {
    // cluster_id 是要发送到的集群的 ID。
    uint64 cluster_id = 1;
}

message ResponseHeader {
    // cluster_id 是发送响应的集群的 ID。
    uint64 cluster_id = 1;
    Error error = 2;
}

enum ErrorType {
    OK = 0;
    UNKNOWN = 1;
    NOT_BOOTSTRAPPED = 2;
    STORE_TOMBSTONE = 3;
    ALREADY_BOOTSTRAPPED = 4;
    INCOMPATIBLE_VERSION = 5;
    REGION_NOT_FOUND = 6;
}

message Error {
    ErrorType type = 1;
    string message = 2;
}

message TsoRequest {
    RequestHeader header = 1;

    uint32 count = 2;
}

message Timestamp {
    int64 physical = 1;
    int64 logical = 2;
}

message TsoResponse {
    ResponseHeader header = 1;

    uint32 count = 2;
    Timestamp timestamp = 3;
}

message BootstrapRequest {
    RequestHeader header = 1;

    metapb.Store store = 2;
}

message BootstrapResponse {
    ResponseHeader header = 1;
}

message IsBootstrappedRequest {
    RequestHeader header = 1;
}

message IsBootstrappedResponse {
    ResponseHeader header = 1;

    bool bootstrapped = 2;
}

message AllocIDRequest {
    RequestHeader header = 1;
}

message AllocIDResponse {
    ResponseHeader header = 1;

    uint64 id = 2;
}

message GetStoreRequest {
    RequestHeader header = 1;

    uint64 store_id = 2;
}

message GetStoreResponse {
    ResponseHeader header = 1;

    metapb.Store store = 2;
    StoreStats stats = 3;
}

message PutStoreRequest {
    RequestHeader header = 1;

    metapb.Store store = 2;
}

message PutStoreResponse {
    ResponseHeader header = 1;
}

message GetAllStoresRequest {
    RequestHeader header = 1;
    // 如果设置为 true，则不返回墓碑状态的 store。
    bool exclude_tombstone_stores = 2;
}

message GetAllStoresResponse {
    ResponseHeader header = 1;

    repeated metapb.Store stores = 2;
}

message GetRegionRequest {
    RequestHeader header = 1;

    bytes region_key = 2;
}

message GetRegionResponse {
    ResponseHeader header = 1;

    metapb.Region region = 2;
    metapb.Peer leader = 3;
    repeated metapb.Peer slaves = 4;
}

message GetRegionByIDRequest {
    RequestHeader header = 1;

    uint64 region_id = 2;
}

// 使用 GetRegionResponse 作为 GetRegionByIDRequest 的响应。

message ScanRegionsRequest {
    RequestHeader header = 1;

    bytes start_key = 2;
    int32 limit = 3; // 当 limit <= 0 时没有限制。
    bytes end_key = 4; // 当 end_key 为空时表示 +inf。
}

message ScanRegionsResponse {
    ResponseHeader header = 1;

    repeated metapb.Region regions = 2;
    repeated metapb.Peer leaders = 3;
}

message GetClusterConfigRequest {
    RequestHeader header = 1;
}

message GetClusterConfigResponse {
    ResponseHeader header = 1;

    metapb.Cluster cluster = 2;
}

message PutClusterConfigRequest {
    RequestHeader header = 1;

    metapb.Cluster cluster = 2;
}

message PutClusterConfigResponse {
    ResponseHeader header = 1;
}

message Member {
    // name 是 Scheduler 成员的名称。
    string name = 1;
    // member_id 是 Scheduler 成员的唯一 id。
    uint64 member_id = 2;
    repeated string peer_urls = 3;
    repeated string client_urls = 4;
    int32 leader_priority = 5;
}

message GetMembersRequest {
    RequestHeader header = 1;
}

message GetMembersResponse {
    ResponseHeader header = 1;

    repeated Member members = 2;
    Member leader = 3;
    Member etcd_leader = 4;
}

message RegionHeartbeatRequest {
    RequestHeader header = 1;

    metapb.Region region = 2;
    // 发送心跳的 Leader Peer。
    metapb.Peer leader = 3;
    // 待处理的 peer 是 leader 无法将其视为
    // 正常工作的 follower 的 peer。
    repeated metapb.Peer pending_peers = 5;
    // Region 的大致大小。
    uint64 approximate_size = 10;
}

message ChangePeer {
    metapb.Peer peer = 1;
    eraftpb.ConfChangeType change_type = 2;
}

message TransferLeader {
    metapb.Peer peer = 1;
}

message RegionHeartbeatResponse {
    ResponseHeader header = 1;

    // 注意，Scheduler 只允许处理上报的 epoch >= 当前 scheduler 的 epoch。
    // Leader peer 定期通过 RegionHeartbeatRequest 向 scheduler 报告 region 状态，
    // scheduler 会决定这个 region 是否应该执行 ChangePeer。
    // 例如，最大 peer 数量为 3，region A，最初 A 中只有 peer 1。
    // 1. Scheduler region 状态 -> Peers (1), ConfVer (1)。
    // 2. Leader peer 1 向 scheduler 报告 region 状态，scheduler 发现
    // peer 数量 < 3，所以首先改变其当前 region
    // 状态 -> Peers (1, 2), ConfVer (1)，并返回 ChangePeer 添加 2。
    // 3. Leader 执行 ChangePeer，然后报告 Peers (1, 2), ConfVer (2)，
    // scheduler 更新其状态 -> Peers (1, 2), ConfVer (2)。
    // 4. Leader 可能在 ConfChange 完成之前向 scheduler 报告旧的 Peers (1), ConfVer (1)，
    // scheduler 仍然响应 ChangePeer 添加 2，当然，我们必须
    // 保证第二个 ChangePeer 不能在 TiKV 中被应用。
    ChangePeer change_peer = 2;
    // Scheduler 可以返回 transfer_leader 让 TiKV 自己执行 leader 转移。
    TransferLeader transfer_leader = 3;
    // Region 的 ID
    uint64 region_id = 4;
    metapb.RegionEpoch region_epoch = 5;
    // 发出对应请求时 region 的 Leader。
    metapb.Peer target_peer = 6;
}

message AskSplitRequest {
    RequestHeader header = 1;

    metapb.Region region = 2;
}

message AskSplitResponse {
    ResponseHeader header = 1;

    // 我们将 region 分裂为两个，第一个使用原始的
    // 父 region id，第二个使用 new_region_id。
    // 我们必须保证 new_region_id 是全局唯一的。
    uint64 new_region_id = 2;
    // 新分裂 region 的 peer id 列表。
    repeated uint64 new_peer_ids = 3;
}

message ReportSplitRequest {
    RequestHeader header = 1;

    metapb.Region left = 2;
    metapb.Region right = 3;
}

message ReportSplitResponse {
    ResponseHeader header = 1;
}

message SplitID {
    uint64 new_region_id = 1;
    repeated uint64 new_peer_ids = 2;
}

message TimeInterval {
    // 此时间段开始的 Unix 时间戳（秒）。
    uint64 start_timestamp = 1;
    // 此时间段结束的 Unix 时间戳（秒）。
    uint64 end_timestamp = 2;
}

message RecordPair {
    string key = 1;
    uint64 value = 2;
}

message StoreStats {
    uint64 store_id = 1;
    // Store 的容量。
    uint64 capacity = 2;
    // Store 的可用大小。
    uint64 available = 3;
    // 此 store 中的 region 总数。
    uint32 region_count = 4;
    // 当前发送快照的数量。
    uint32 sending_snap_count = 5;
    // 当前接收快照的数量。
    uint32 receiving_snap_count = 6;
    // Store 启动时间（Unix 时间戳，秒）。
    uint32 start_time = 7;
    // 正在应用快照的 region 数量。
    uint32 applying_snap_count = 8;
    // Store 是否繁忙。
    bool is_busy = 9;
    // 数据库实际使用的空间。
    uint64 used_size = 10;
    // 实际报告的时间间隔。
    TimeInterval interval = 15;
    // Store 中线程的 CPU 使用率。
    repeated RecordPair cpu_usages = 16;
    // Store 中线程的磁盘读 I/O 速率。
    repeated RecordPair read_io_rates = 17;
    // Store 中线程的磁盘写 I/O 速率。
    repeated RecordPair write_io_rates = 18;
    // Store 中操作的延迟。
    repeated RecordPair op_latencies = 19;
}

message StoreHeartbeatRequest {
    RequestHeader header = 1;

    StoreStats stats = 2;
}

message StoreHeartbeatResponse {
    ResponseHeader header = 1;
}

message ScatterRegionRequest {
    RequestHeader header = 1;

    uint64 region_id = 2;

    // 如果 Scheduler 找不到该 region，将使用这些 region 信息。
    // 例如，region 刚刚分裂，尚未向 Scheduler 报告。
    metapb.Region region = 3;
    metapb.Peer   leader = 4;
}

message ScatterRegionResponse {
    ResponseHeader header = 1;
}

message GetGCSafePointRequest {
    RequestHeader header = 1;
}

message GetGCSafePointResponse {
    ResponseHeader header = 1;

    uint64 safe_point = 2;
}

message UpdateGCSafePointRequest {
    RequestHeader header = 1;

    uint64 safe_point = 2;
}

message UpdateGCSafePointResponse {
    ResponseHeader header = 1;

    uint64 new_safe_point = 2;
}

message GetOperatorRequest {
   RequestHeader header = 1;
   uint64 region_id = 2;
}

enum OperatorStatus {
	SUCCESS = 0;
	TIMEOUT = 1;
	CANCEL  = 2;
	REPLACE = 3;
	RUNNING = 4;
}

message GetOperatorResponse {
    ResponseHeader header = 1;
    uint64 region_id = 2;
    bytes desc = 3;
    OperatorStatus status = 4;
    bytes kind = 5;
}
